### ISSUE TITLE
Use byte32 for subnet name

### ISSUE THREAD

**Issue by dnkolegov** [LimeChain/filecoin-ipc-actors-fevm#53]
The subnet name is an arbitrary string set by a user. 
Restrict the length of the subnet name by 32 characters.
That will be more efficient from a gas perspective.

https://github.com/consensus-shipyard/ipc-actors/issues/108

**Comment by mikirov** [comment]
Fixed in https://github.com/LimeChain/filecoin-ipc-actors-fevm/pull/47
