### ISSUE TITLE
Constructor function does not check for zero address ipcGatewayAddr

### ISSUE THREAD

**Issue by dnkolegov** [LimeChain/filecoin-ipc-actors-fevm#55]
Constructor function does not check for zero address ipcGatewayAddr - https://github.com/LimeChain/filecoin-ipc-actors-fevm/blob/d247b20a4dd6ff41c6b9efad142cc05ffc2f8853/src/SubnetActor.sol#L152

**Comment by mikirov** [comment]
Fixed in https://github.com/LimeChain/filecoin-ipc-actors-fevm/pull/73/
