### ISSUE TITLE
Constructor function does not check for validity of consensus 

### ISSUE THREAD

**Issue by dnkolegov** [LimeChain/filecoin-ipc-actors-fevm#57]
Constructor function does not check for validity of consensus - https://github.com/LimeChain/filecoin-ipc-actors-fevm/blob/d247b20a4dd6ff41c6b9efad142cc05ffc2f8853/src/SubnetActor.sol#L153
Suggestion: remove all consensus types other than Mir.

**Comment by mikirov** [comment]
The consensus type enum is tranfered from the Rust implementation, even though we don't check against these values. Do we want to keep them or remove the unused ones? @adlrocha
