### ISSUE TITLE
Do not use this.balance

### ISSUE THREAD

**Issue by dnkolegov** [LimeChain/filecoin-ipc-actors-fevm#58]
SubnetActor’s kill method uses `this.balance`. 
It is not [recommended](https://github.com/sigp/solidity-security-blog#3-unexpected-ether-1) practice. An attacker can send some ETH, and the subnet will not be killed. 

Suggestion: check CircSupply and TotalStake instead of the balance.

**Comment by mikirov** [comment]
Fixed in https://github.com/LimeChain/filecoin-ipc-actors-fevm/pull/73/
