### ISSUE TITLE
Several functions in the code lack documentation

### ISSUE THREAD

**Issue by dnkolegov** [LimeChain/filecoin-ipc-actors-fevm#66]
For example:
- setMembership
- submitCheckpoint
- submitTopDownCheckpoint
- _submitTopDownVote
- _markMostVotedSubmissionExecuted
- _commitCheckpoint

**Comment by mikirov** [comment]
Fixed in https://github.com/LimeChain/filecoin-ipc-actors-fevm/pull/73/
